In [19]:
from tqdm import tqdm

In [20]:
import os
from itertools import combinations
import face_recognition
import numpy as np
import os
import shutil

In [21]:
picture_names = os.listdir("output_cacd_has_under18")
file_names = picture_names
picture_names = [picture_name.split(".")[0] for picture_name in picture_names]
picture_names = [picture_name.split("_") for picture_name in picture_names]

In [22]:
print(file_names[1])
print(picture_names[1])

24_Nicole_'Snooki'_Polizzi_0004.jpg
['24', 'Nicole', "'Snooki'", 'Polizzi', '0004']


In [23]:
print(range(len(picture_names)))

range(0, 23714)


In [24]:
# {name:{age:[file name], age:[file name, file name], name:{...}}}
celebrity_dic = {}
for i in range(len(picture_names)):
    pic = picture_names[i]
    age = pic[0]
    name = "".join(pic[1:-1])
   
    if name not in celebrity_dic:
        different_age = {}
        different_age[age] = [file_names[i]]
        celebrity_dic[name] = different_age
    else:
        # this cele has in dic 
        if age in celebrity_dic[name]:
            celebrity_dic[name][age].append(file_names[i])
        else:   
            celebrity_dic[name][age] = [file_names[i]]   

In [25]:
for name in tqdm(celebrity_dic.keys()):
    destination = "dump"
    source = "output_cacd_has_under18/"
    for age in celebrity_dic[name].keys():
        pic_filenames = celebrity_dic[name][age]

        for pic_filename in pic_filenames:
            path = os.path.join("output_cacd_has_under18", pic_filename)
            image = face_recognition.load_image_file(path)
            image_encoding = face_recognition.face_encodings(image)
            if not image_encoding:
                pic_filenames.remove(pic_filename)
                shutil.move(source+pic_filename,destination)

        combs = list(combinations(pic_filenames,2))
        # Compare combinations of images samilarities
        face_distances = []
        for comb in range(len(combs)):
            image1 = face_recognition.load_image_file(os.path.join("output_cacd_has_under18", combs[comb][0]))
            image2 = face_recognition.load_image_file(os.path.join("output_cacd_has_under18", combs[comb][1]))
            try:
                image1_encoding = face_recognition.face_encodings(image1)[0]
                image2_encoding = face_recognition.face_encodings(image2)[0]
                distances = face_recognition.face_distance([image1_encoding], image2_encoding)
                face_distances.append(distances)
            except:
                print(image1)
                print(image2)
                print(comb,"stoped")
                continue
   
        if all(np.array(face_distances) > 0.65):
            for pic_filename in pic_filenames:
                shutil.move(source+pic_filename,destination)
        else:
            # find min combination and take one
            min_distance_index = face_distances.index(min(face_distances))
            base_pic = combs[min_distance_index][0]
            left_pic_filenames = pic_filenames.remove(base_pic)

            image1 = face_recognition.load_image_file(source+base_pic)
            image1_encoding = face_recognition.face_encodings(image1)[0]

            if left_pic_filenames:
                for left_pic_filename in left_pic_filenames:
                    image2 = face_recognition.load_image_file(left_pic_filename)
                    image2_encoding = face_recognition.face_encodings(image2)[0]

                    face_distances = face_recognition.face_distance([image1_encoding], image2_encoding)

                    if face_distances > 0.65:
                        shutil.move(source+left_pic_filename,destination+pic_filename)

 19%|███████▌                                | 66/351 [27:06<1:37:13, 20.47s/it]

[[[  5   5   5]
  [  4   4   4]
  [  5   5   5]
  ...
  [ 21  21  21]
  [ 16  16  16]
  [ 13  13  13]]

 [[ 14  14  14]
  [ 16  16  16]
  [ 19  19  19]
  ...
  [ 14  14  14]
  [ 12  12  12]
  [ 10  10  10]]

 [[ 17  17  17]
  [ 22  22  22]
  [ 32  32  32]
  ...
  [ 10  10  10]
  [  9   9   9]
  [ 10  10  10]]

 ...

 [[101 101 101]
  [103 103 103]
  [108 108 108]
  ...
  [  9   9   9]
  [  4   4   4]
  [  0   0   0]]

 [[102 102 102]
  [105 105 105]
  [110 110 110]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[103 103 103]
  [106 106 106]
  [112 112 112]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
[[[26 27 22]
  [26 27 22]
  [26 27 22]
  ...
  [37 33 30]
  [37 33 30]
  [37 33 30]]

 [[25 26 21]
  [25 26 21]
  [25 26 21]
  ...
  [36 32 29]
  [36 32 29]
  [36 32 29]]

 [[25 26 21]
  [25 26 21]
  [25 26 21]
  ...
  [36 32 29]
  [36 32 29]
  [36 32 29]]

 ...

 [[13 15 14]
  [14 15 17]
  [15 16 18]
  ...
  [19 21 18]
  [19 21 18]
  [19 21 18]]

 [[14 15 17]
  [14 1

 95%|█████████████████████████████████████  | 333/351 [2:14:26<04:30, 15.05s/it]

[[[227 239 235]
  [225 237 233]
  [229 241 237]
  ...
  [155 114  96]
  [169 128 110]
  [182 140 124]]

 [[226 238 234]
  [226 238 234]
  [227 240 233]
  ...
  [147 106  88]
  [156 115  97]
  [167 124 107]]

 [[222 234 230]
  [225 238 231]
  [225 238 231]
  ...
  [139  98  78]
  [143 100  81]
  [149 106  87]]

 ...

 [[208 203 181]
  [199 194 174]
  [189 186 167]
  ...
  [172 183 167]
  [173 182 165]
  [175 184 167]]

 [[201 195 179]
  [194 191 174]
  [188 185 170]
  ...
  [170 181 167]
  [163 174 160]
  [150 161 147]]

 [[194 188 174]
  [190 186 174]
  [186 184 171]
  ...
  [166 178 164]
  [148 158 147]
  [117 127 116]]]
[[[32 33 61]
  [28 30 55]
  [30 32 57]
  ...
  [38 39 67]
  [37 38 66]
  [38 39 67]]

 [[30 31 59]
  [27 29 54]
  [28 30 55]
  ...
  [37 38 66]
  [36 37 65]
  [37 38 66]]

 [[29 30 58]
  [27 29 54]
  [26 28 53]
  ...
  [38 39 67]
  [38 39 67]
  [38 39 67]]

 ...

 [[66 67 85]
  [67 68 86]
  [67 68 86]
  ...
  [69 68 82]
  [66 65 79]
  [67 66 80]]

 [[67 68 86]
  [67 6

 97%|█████████████████████████████████████▊ | 340/351 [2:16:20<03:15, 17.81s/it]

[[[254 252 253]
  [252 250 251]
  [251 249 250]
  ...
  [242 240 241]
  [245 244 242]
  [250 249 247]]

 [[255 254 255]
  [253 251 252]
  [252 250 251]
  ...
  [246 244 245]
  [249 248 246]
  [253 252 250]]

 [[255 254 255]
  [253 251 252]
  [251 249 250]
  ...
  [248 246 247]
  [251 250 248]
  [255 255 253]]

 ...

 [[ 20  26  60]
  [ 18  24  58]
  [ 21  27  61]
  ...
  [254 255 255]
  [254 255 255]
  [254 255 255]]

 [[ 19  25  59]
  [ 17  23  57]
  [ 21  27  61]
  ...
  [254 255 255]
  [254 255 255]
  [254 255 255]]

 [[ 19  25  59]
  [ 16  22  56]
  [ 21  27  61]
  ...
  [254 255 255]
  [253 254 255]
  [253 254 255]]]
[[[ 32  18  17]
  [ 29  15  14]
  [ 29  15  14]
  ...
  [126 125 139]
  [126 125 139]
  [126 125 139]]

 [[ 29  18  16]
  [ 30  16  15]
  [ 29  15  14]
  ...
  [126 125 139]
  [126 125 139]
  [126 125 139]]

 [[ 27  16  14]
  [ 30  16  15]
  [ 29  15  12]
  ...
  [126 125 139]
  [126 125 139]
  [126 125 139]]

 ...

 [[ 85  51  42]
  [ 85  51  42]
  [ 84  50  41]
  ..

 99%|██████████████████████████████████████▍| 346/351 [2:18:33<02:00, 24.03s/it]


UnidentifiedImageError: cannot identify image file 'output_cacd_has_under18/.DS_Store'